#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---

- name: Create chaparone sanity test project directory
  sudo: no
  file: path="{{ jenkins_home_path }}/jobs/Chaparone_Sanity/" state="directory"

- name: Set up chaparone sanity test project
  sudo: no
  template:
    src: chaparone_sanity.config.xml.j2
    dest: "{{ jenkins_home_path }}/jobs/Chaparone_Sanity/config.xml"
    force: "yes"
