#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: Ensure Jenkins Home dir exists with correct ownership
  file: path="{{jenkins_home_path}}" owner="{{ansible_ssh_user}}" state=directory

- name: Ensure assets_cache dir exists on Jenkins host for iso and ovf file caches
  file: path="{{jenkins_asset_cache_path}}" owner="{{ansible_ssh_user}}" state=directory

- name: Docker requires docker-py
  pip: name=docker-py

- name: Set jenkins.model.JenkinsLocationConfiguration.xml
  template:
    src: jenkins.model.JenkinsLocationConfiguration.xml.j2
    dest: "{{ jenkins_home_path }}/jenkins.model.JenkinsLocationConfiguration.xml"
    force: "yes"

- name: Jenkins Container
  docker:
    name: "{{jenkins_container_name}}"
    image: openedge/jenkins
    state: reloaded
    ports:
    - "8080:8080"
    volumes:
    - "{{jenkins_home_path}}:/var/jenkins_home"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "$(which docker):/usr/bin/docker"

- name: specify additional plugin scm-api
  lineinfile: dest={{jenkins_home_path}}/plugins.txt line="scm-api" create="yes"

- name: install additional plugins
  sudo: yes
  command: "docker exec -t {{jenkins_container_name}} /usr/local/bin/plugins.sh /var/jenkins_home/plugins.txt"




