#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---

- include: configure_gerrit.yml
  when: jenkins_gerrit_server_fqdn != ""

- include: chaperone_projects.yml
- include: install.yml
